config/routes.rb
Rails.application.routes.draw do

  get 'messages/create'
  devise_for :parent_users, controllers: {
    sessions: 'parent_users/sessions',
    registrations: 'parent_users/registrations'
  }

  devise_for :teacher_users, controllers: {
    sessions: 'teacher_users/sessions',
    registrations: 'teacher_users/registrations'
  }

  resources :contacts

  resources :messages, only: [:create ]

  root to: "contacts#index"

end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :parent_user
  has_one_attached :image
  has_many :messages

  with_options presence: true do
    validates :image
    validates :class_id
    validates :last_name_c_j
    validates :first_name_c_j
    validates :last_name_c_k
    validates :first_name_c_k
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_parent_user!, except: [:show, :index ]

  def destroy
    contact =Contact.find(params[:id])
    contact.destroy
    redirect_to root_path
  end

  def index
    @contacts = Contact.all
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    contact = Contact.find(params[:id])
    if contact.update(contact_params)
      redirect_to contact_path(contact.id), method: :get
    else
      render edit
    end
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.create(contact_params)
    if @contact.save
      redirect_to root_path
    else
      render new_contact_path
    end
  end


private
def contact_params
  params.require(:contact).permit(:image, :class_id, :last_name_c_j, :first_name_c_j, :last_name_c_k, :first_name_c_k ).merge(parent_user_id: current_parent_user.id)
end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact.html.erb
  <%= link_to image_tag(contact.image, class: :card__img ), contact_path(contact.id) %>

    <%= link_to "#{contact.first_name_c_j}ちゃんの連絡帳", contact_path(contact.id) , class: :card__user %>

app/views/contacts/_form.html.erb
<%= form_with(model: @contact, local: true) do |f|%>

 <div class="field">
    <%= f.label :class_id, "お子さんのクラス" %><br />
    <%= f.text_field :class_id %>
  </div>

  <div class="field">
    <%= f.label :last_name_c_j, "お子さんの名前（名字）" %><br />
    <%= f.text_field :last_name_c_j %>
  </div>

  <div class="field">
    <%= f.label :first_name_c_j, "お子様の名前（名前）" %><br />
    <%= f.text_field :first_name_c_j, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :last_name_c_k, "お子さんの名字（カナ）" %><br />
    <%= f.text_field :last_name_c_k %>
  </div>

  <div class="field">
    <%= f.label :first_name_c_k, "お子様の名前（カナ）" %><br />
    <%= f.text_field :first_name_c_k, class: :form__text %>
  </div>
 
  <div class="field">
    <%= f.label :image, "お子様の写真" %><br />
    <%= f.file_field :image %>
  </div>


  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
   <div class="form__wrapper">
      <h2 class="page-heading">連絡帳の編集</h2>
      <%= render partial: "form", locals: { prototype: @prototype } %>
    </div>

app/views/contacts/index.html.erb
<h1>トップページ</h1>

<h4>こんにちは！　ミマモル保育園です</h4>

<%= image_tag '子供イラスト.png', size: "600x350" %>

<%= render partial: 'contact', collection: @contacts %>

app/views/contacts/new.html.erb
<div class="form__wrapper">
  <h2 class="page-heading">新規連絡帳の作成ページ</h2>
    <%# 部分テンプレートでフォームを表示する %>
  <%= render partial: "form" %>
</div>

app/views/contacts/show.html.erb
<%=  "#{@contact.first_name_c_j}ちゃんのページ" %>

 <div class="prototype__image">
        <%= image_tag @contact.image %>
</div>

       <% if parent_user_signed_in? && current_parent_user.id == @contact.parent_user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_contact_path(@contact.id), class: :prototype__btn %>
          <%= link_to "削除する", contact_path(@contact.id), method: :delete, class: :prototype__btn %>
        </div>
       <% end %>